#!/usr/bin/env node
// build-content.mjs — compiles content/ into a single generated TypeScript module that
// gets bundled into the server. This is deliberate: the MCP route must NEVER read the
// filesystem at request time (Next.js output-file-tracing drops content/ on Vercel — the
// classic "works locally, 404s in prod" trap). Everything the server serves is embedded here.
//
// The manifest is DERIVED from the directory listing — no hand-maintained index files.
// content/schema/ and content/archive/ are excluded from the active manifest.
//
// Run automatically before `next build` (see package.json prebuild) and re-run whenever
// content changes: `node scripts/build-content.mjs`.

import { readFile, readdir, mkdir, writeFile, stat } from 'node:fs/promises';
import { join, dirname, relative, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO = join(__dirname, '..');
const CONTENT = join(REPO, 'content');
const OUT = join(REPO, 'src', 'generated', 'content.ts');

const EXCLUDE_DIRS = new Set(['schema', 'archive']);

async function walk(dir, acc = []) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    const rel = relative(CONTENT, full);
    const top = rel.split('/')[0];
    if (entry.isDirectory()) {
      if (EXCLUDE_DIRS.has(entry.name)) continue;
      await walk(full, acc);
    } else if (rel.includes('/') ? !EXCLUDE_DIRS.has(top) : true) {
      acc.push(full);
    }
  }
  return acc;
}

// minimal frontmatter parse: leading --- ... --- block of key: value lines
function parseFrontmatter(text) {
  if (!text.startsWith('---\n')) return { frontmatter: {}, body: text };
  const end = text.indexOf('\n---', 4);
  if (end === -1) return { frontmatter: {}, body: text };
  const block = text.slice(4, end);
  const body = text.slice(end + 4).replace(/^\n/, '');
  const fm = {};
  for (const line of block.split('\n')) {
    const m = line.match(/^([A-Za-z0-9_]+):\s?(.*)$/);
    if (m) fm[m[1]] = m[2].replace(/^["']|["']$/g, '');
  }
  return { frontmatter: fm, body };
}

async function main() {
  const files = (await walk(CONTENT)).sort();
  const documents = {}; // markdown: key -> {path, frontmatter, body}
  const data = {};      // json: key -> parsed
  const docPaths = [];
  const dataKeys = [];
  const seasons = [];

  for (const file of files) {
    const rel = relative(CONTENT, file);
    const ext = extname(file);
    const raw = await readFile(file, 'utf8');
    if (ext === '.json') {
      const key = rel.replace(/\.json$/, '');
      data[key] = JSON.parse(raw);
      dataKeys.push(key);
      if (key.startsWith('seasons/')) seasons.push(key.replace('seasons/', ''));
    } else if (ext === '.md') {
      const key = rel.replace(/\.md$/, '');
      const { frontmatter, body } = parseFrontmatter(raw);
      documents[key] = { path: rel, frontmatter, body };
      docPaths.push(key);
    }
  }

  const header = `// GENERATED by scripts/build-content.mjs — DO NOT EDIT.\n` +
    `// Re-run: node scripts/build-content.mjs\n\n`;
  const body = [
    `export const generatedAt = ${JSON.stringify(new Date().toISOString())};`,
    ``,
    `export interface Document { path: string; frontmatter: Record<string, string>; body: string; }`,
    ``,
    `export const documents: Record<string, Document> = ${JSON.stringify(documents, null, 2)};`,
    ``,
    `export const data: Record<string, unknown> = ${JSON.stringify(data, null, 2)};`,
    ``,
    `export const manifest = {`,
    `  documents: ${JSON.stringify(docPaths)},`,
    `  data: ${JSON.stringify(dataKeys)},`,
    `  seasons: ${JSON.stringify(seasons.sort())},`,
    `} as const;`,
    ``,
  ].join('\n');

  await mkdir(dirname(OUT), { recursive: true });
  await writeFile(OUT, header + body, 'utf8');
  console.log(`[build-content] wrote ${relative(REPO, OUT)} — ${docPaths.length} docs, ${dataKeys.length} data files, seasons: ${seasons.sort().join(', ')}`);
}

main().catch(err => { console.error('[build-content] FAILED', err); process.exit(1); });
